Return invoice on successful lnurl-withdraw
breez/breez-sdk pull request #436
Opened 2023-09-07 10:44 UTC by ok300

Include the `LNInvoice` as inner data in the `Ok` result of `BreezServices::lnurl_withdraw`.

Subtasks:
- [x] uniffi
- [x] flutter bridge
- [ ] React Native bindings

Fixes #427

2023-09-07 10:50 UTC, ok300 commented
@roeierez it's ready for review.

I will add the RN bindings as last step, once we agree on the general structure.

2023-09-07 11:04 UTC, dangeross commented
> I will add the RN bindings as last step, once we agree on the general structure.

It could be the first use of the RN codegen 😎

2023-09-07 11:07 UTC, ok300 commented
The PR simply adds the invoice in the withdraw `Ok` response.

However, if the goal is to be able to link a payment with a LNURL-withdraw request, an alternative way to do this is to extend `LnPaymentDetails`, which is a field of `Payment`

https://github.com/breez/breez-sdk/blob/41b3a01321b79ffc576755fa5ec24c80b959d5a0/libs/sdk-core/src/models.rs#L661-L678

with an `lnurl_withdraw_endpoint: Optional<String>`, where we can store the LNURL-w endpoint associated with this `Payment`.

That may be preferable to the approach in this PR, because in the PR the LNURL handling is inconsistent:
- `lnurl_pay` result has no reference to the invoice, but `LnPaymentDetails` has a few pay-related optional fields: https://github.com/breez/breez-sdk/blob/41b3a01321b79ffc576755fa5ec24c80b959d5a0/libs/sdk-core/src/models.rs#L669-L677
- `lnurl_withdraw` has the reverse: invoice in the service call result, but no reference in the `Payment`

What do you think? Is the PR approach ok? Or better switch to the above? Or do both?

2023-09-08 08:56 UTC, danielgranhao commented
If possible, as a user, I would like to have both :) that way, I can avoid always searching for the correct payment after making an LNURL withdrawal.

Otherwise, the withdrawal flow is: 
1.  Start withdrawal
2. Search for the created payment associated with the withdrawal
3. Wait for `BreezEvent::InvoicePaid` that includes the hash of the withdrawal payment

If we have what the current version of this PR proposes, the middle step can be discarded.

2023-09-15 13:51 UTC, ok300 commented
@dangeross I took your RN generator for a test-drive and ran it on this PR.

Can you please doublecheck if all looks good? fe8884de178d4135b64f13f1a80c8224c079ccb5

2023-09-15 14:27 UTC, dangeross approved these changes
Looks good in general. There seems to be lots of linting changes with the kotlin files though. Can you give me your ktlint and kotlin versions?
```
ktlint --version
kotlin -version
```

2023-09-15 14:34 UTC, ok300 commented
> ktlint --version

1.0.0

> kotlin -version

Kotlin version 1.9.10-release-459 (JRE 20.0.2)

2023-09-15 14:43 UTC, dangeross commented
> > ktlint --version
>
> 1.0.0

Ok, seems to be a version difference. I've upgraded to 1.0.0

2023-09-17 05:54 UTC, roeierez commented
@ok300 the PR looks good to me. As for your comment above do you want to add the step of associated the withdraw endpoint with the payment in the storage or not?  Another option is in a separate PR.

2023-09-17 05:55 UTC, roeierez approved these changes
LGTM! We need a corresponding c-breez PR as I believe this breaks it.

2023-09-18 08:53 UTC, ok300 commented
> If possible, as a user, I would like to have both :)

Then I'll add both in this PR.

2023-09-20 20:05 UTC, roeierez requested changes
Looks good! Dropped a NIT comment.

2023-09-20 20:05 UTC, roeierez commented on libs/sdk-core/src/models.rs
> +pub enum LnUrlWithdrawCallbackStatus {
Perhaps if we are introducing new types here we can use better naming?
`LnUrlWithdrawCallbackStatus`  => `LnUrlWithdrawResult`
`LnUrlWithdrawOkData`  => `LnurlWithdrawSuccess`
`LnUrlErrorData`  => `LnurlError`

2023-09-21 12:51 UTC, erdemyerebasmaz commented
@ok300 @roeierez 
Shouldn't we apply these naming changes to LnUrlCallbackStatus used on lnurl_auth as well?

2023-09-21 12:57 UTC, ok300 commented
@erdemyerebasmaz how about `LnUrlCallbackStatus` => `LnUrlCallbackResult` ?

It's used not only in LNURL-auth, but also as intermediary step in LNURL-withdraw.

2023-09-21 13:03 UTC, erdemyerebasmaz commented
> @erdemyerebasmaz how about `LnUrlCallbackStatus` => `LnUrlCallbackResult` ?
> 
> It's used not only in LNURL-auth, but also as intermediary step in LNURL-withdraw.

@ok300 I see, isn't it supposed to be `LnUrlResult` according to:

> Perhaps if we are introducing new types here we can use better naming? 
`LnUrlWithdrawCallbackStatus` => `LnUrlWithdrawResult` 
`LnUrlWithdrawOkData` => `LnurlWithdrawSuccess` 
`LnUrlErrorData` => `LnurlError`

2023-09-21 13:12 UTC, erdemyerebasmaz commented
> Well, there are 2 naming conventions which don't overlap:
> 
> * one is for the LNURL-withdraw specific case. Calling the struct `LnUrlWithdrawResult` makes sense.
> * one is for a generic case that affects several callback types. `LnUrlResult` gives the wrong impression that its what a LNURL-workflow is supposed to end in, but it's only the case for auth. It's an intermediary result in withdraw. IMO `LnUrlCallbackResult` better captures the nature if it.

Thanks for the clarification, second item was what made it confusing for me. If that's the case, I see no issue with keeping `LnUrlCallbackStatus` as it is.

2023-09-21 13:17 UTC, ok300 commented
Then @roeierez  this PR is ready for final review.

I also linked the c-breez PR by @erdemyerebasmaz in the description above.

2023-09-21 21:45 UTC, dangeross approved these changes
Looks good!

2023-09-22 17:42 UTC, roeierez approved these changes
LGTM

2023-09-23 07:55 UTC, merged