Expose exemptfee in the SDK Config struct
breez/breez-sdk pull request #440
Opened 2023-09-07 12:01 UTC by ok300

Fixes #438

2023-09-07 13:11 UTC, JssDWt approved these changes
LGTM

2023-09-09 08:49 UTC, roeierez requested changes
Looks good. React Native is missing.

2023-09-10 15:21 UTC, roeierez approved these changes
LGTM

2023-09-10 15:27 UTC, dangeross requested changes

2023-09-10 15:27 UTC, dangeross commented on libs/sdk-react-native/android/src/main/java/com/breezsdk/BreezSDKMapper.kt
> +        return Config(breezserver, mempoolspaceUrl, workingDir, asNetwork(network), paymentTimeoutSec.toUInt(), defaultLspId, apiKey, maxfeePercent, exemptfeeMsat, nodeConfig)
I think it needs converting to a ULong

2023-09-10 15:27 UTC, dangeross commented on libs/sdk-react-native/ios/BreezSDKMapper.swift
> +           let exemptfeeMsat = config["exemptfeeMsat"] as? Double {
Can be as UInt64

2023-09-10 15:35 UTC, ok300 commented on libs/sdk-react-native/android/src/main/java/com/breezsdk/BreezSDKMapper.kt
> +        return Config(breezserver, mempoolspaceUrl, workingDir, asNetwork(network), paymentTimeoutSec.toUInt(), defaultLspId, apiKey, maxfeePercent, exemptfeeMsat, nodeConfig)
Done

2023-09-10 15:35 UTC, ok300 commented on libs/sdk-react-native/ios/BreezSDKMapper.swift
> +           let exemptfeeMsat = config["exemptfeeMsat"] as? Double {
Done

2023-09-10 15:41 UTC, dangeross approved these changes

2023-09-10 15:54 UTC, merged