fix flacky tests
breez/breez-sdk pull request #486
Opened 2023-09-26 12:50 UTC by Torakushi

We added some flacky tests when testing ln_url callback.
The problem was that we ran the tests in parallel and possibly mocked the same URL twice (leading to interference)

2023-09-26 17:06 UTC, ok300 requested changes
Looks good.

The only thing remaining is to fix the `cargo clippy` warnings.

2023-09-27 07:36 UTC, Torakushi commented
@ok300 Clippy wasn't happy with functions with too much arguments

I've created two structures that will be passed as argument to our different functions

2023-09-27 13:29 UTC, ok300 approved these changes

2023-09-27 13:49 UTC, ok300 requested changes
I've ran this a few times and about once every 5-10 runs, I get

```
failures:

---- input_parser::tests::test_lnurl_withdraw_lud_17_error stdout ----
Error: Unrecognized input type
```

There must be something about the order of tests, or which tests get executed in parallel, that causes this.

2023-09-27 14:06 UTC, ok300 commented
I mean, in principle, the tests are not flaky, because they run well one test at a time:

```
cargo test -- --test-threads=1
```

AFAIK the CI is also doing that, by reserving only 1 CPU to the workflow that calls `cargo test`.

So there is always the option of keeping it as it is, and running the tests sequentially.

2023-09-27 14:18 UTC, Torakushi commented
Yes, that's true, it's only when we run tests in parallel.

The problem with `cargo test -- --test-threads=1` is that if we have many more tests, it will take forever. It's okay for the CI, but for local development it can be annoying :/ (But it's not really annoying at the moment, so it depends on what we want!)

2023-09-28 07:10 UTC, Torakushi commented
So, I solved the concurrency problem in the tests. Essentially, when testing an error case, we don't need to provide a "real" url as we will not decode the lnurl to check if the url matches.
I added a comment for the HTTP_MOCK_SERVER to warn against this problem.

PS: Sharing a mock server might not be ideal because of this. Mocking the http server directly can be a solution (like Jesse suggested).

2023-09-28 07:37 UTC, JssDWt commented
> Sharing a mock server might not be ideal because of this. Mocking the http server directly can be a solution (like Jesse suggested).

Yeah I suggested mocking the http client actually, so you can inspect the request in the test, rather than having a shared server.

2023-09-28 07:45 UTC, Torakushi commented
Yes sorry for the typo!
`Mocking the http server directly --> Mocking the http client directly`

2023-09-28 07:50 UTC, JssDWt approved these changes

2023-10-02 07:56 UTC, JssDWt commented
@ok300 review reminder

2023-10-02 08:06 UTC, ok300 approved these changes

2023-10-02 08:25 UTC, merged