Fix rev swap edge case affecting offline nodes
breez/breez-sdk pull request #492
Opened 2023-09-29 15:09 UTC by ok300

Before this PR, the following scenario could occur:
- reverse swap is started and goes into `InProgress` state
- lockup tx is confirmed, claim tx is broadcasted
  - before the next `sync`, the node goes offline (rev swap state is still `InProgress`)
- claim tx gets confirmed
- node comes back online and executes the loop below for monitored rev swaps (incl. the above `InProgress` one)
  - it tries to re-broadcast the claim tx, calling `create_claim_tx`
  - however `create_claim_tx` relies on utxos to calculate the total confirmed amount which should be sent in the claim tx
  - since the claim tx is already confirmed, thus spending the available utxo in the lockup address, this means no utxos in the lockup address are found
  - this leads to a panic, because with total amount of 0 we try to subtract mining fees, which gives a negative result, which is not allowed for a tx value

With this PR, we only attempt to create and build the claim tx if it's not already confirmed.

If it is confirmed, this step is skipped. On the next `sync`, the `InProgress` rev swaps will automatically transition to `CompletedConfirmed`.

2023-09-29 15:39 UTC, ok300 commented
Will mark it as a draft until I test it in several configurations.

2023-09-29 21:48 UTC, roeierez requested changes

2023-09-29 21:48 UTC, roeierez commented on libs/sdk-core/src/reverseswap.rs
> +            match claim_tx_status {
In a glance it looks correct but one thing is unclear to me: 
The  `execute_pending_reverse_swaps` is only called after `refresh_monitored_reverse_swaps` so the question is why the status wasn't updated to Completed? Shouldn't the provider return Completed here (https://github.com/breez/breez-sdk/blob/main/libs/sdk-core/src/reverseswap.rs#L475) in this case?

2023-10-02 17:56 UTC, roeierez commented
The question is now that the state transition was fixed: https://github.com/breez/breez-sdk/pull/496
Do we really need this PR? 
It seems a claim confirmed swaps won't be listed in the monitored anymore and won't enter the `execute_pending_reverse_swaps`

2023-10-03 09:21 UTC, ok300 commented
Correct. Makes sense, plus I tested and works, so I'll drop this.

2023-10-03 09:21 UTC, closed without merging