Validate bolt11 network
breez/breez-sdk pull request #586
Opened 2023-11-06 16:00 UTC by dangeross

This PR adds the invoice network to the LNInvoice response of `parse_input` and `parse_invoice`. It also validates the bolt11 invoice network against the config network when calling `send_payment` or `lnurl_pay`.

- [x] Validate send_payment
- [ ] Validate lnurl_pay

Fixes #462

2023-11-13 11:53 UTC, ok300 approved these changes

2023-11-13 15:22 UTC, roeierez requested changes

2023-11-13 15:22 UTC, roeierez commented on libs/sdk-core/src/invoice.rs
> +pub fn parse_invoice(bolt11: &str, network: Option<Network>) -> InvoiceResult<LNInvoice> {
This change makes the binding interface different than the rust interface (we added one parameter only to the rust layer).
I am not sure we should overload the upper layer validation down to this function. Perhaps we should validate on the caller instead?

2023-11-15 12:23 UTC, roeierez reviewed
Looks good and simple! Dropped one simplification suggestion.

2023-11-15 12:23 UTC, roeierez commented on libs/sdk-core/src/invoice.rs
> +    if bolt11.trim().is_empty() {
We duplicate the parse_invoice code here. Perhaps we should just use it and compare the network with the LNInvoice object?

2023-11-15 14:29 UTC, roeierez approved these changes
LGTM

2023-11-15 20:15 UTC, merged