Return success on failure to decrypt AES success action
breez/breez-sdk pull request #637
Opened 2023-11-23 11:54 UTC by andrei-21

If there is an AES success action in `payRequest` (LUD-10) then failure to decrypt ciphertext should not fail the payment, since the funds were actually sent and the lightning payment has succeeded.

Solves #632.

2023-11-23 13:11 UTC, ok300 commented on libs/sdk-core/src/lnurl/pay.rs
> +            result: Result<AesSuccessActionDataDecrypted, String>,
`Result` is a good direction, try to use a`Result`-like enum with an inner field. These play better with bindings and uniffi AFAIK.

Something like

```rust
    pub enum AesSuccessActionDataResult {
        Decrypted { data: AesSuccessActionDataDecrypted },
        Error { data: String }
    }
```

To propagate the changes to the bindings for other languages, you'd have to
- update `breez_sdk.udl`
- run `cargo build` in `sdk-bindings`
- run `make init` / `make dev` in `sdk-flutter`
- run the command listed in the README of https://github.com/breez/breez-sdk-rn-generator

2023-11-24 12:09 UTC, dangeross reviewed
Overall looks good I think, just some comments around the error variant variables

2023-11-24 16:01 UTC, ok300 requested changes
Looks good!

Could you please also add a short test case for when decryption fails?

There is `test_lnurl_pay_aes_success_action` that covers the success scenario, I imagine a similar one can check the new result type in case of failed decryption.

2023-11-25 08:16 UTC, ok300 approved these changes
My bad, I missed it.

Then it's all good!

2023-11-25 09:59 UTC, roeierez approved these changes
LGTM

2023-11-25 09:59 UTC, merged