enhancement: sort fiat currencies in API by name, add docs
breez/breez-sdk pull request #686
Opened 2023-12-12 19:19 UTC by rustaceanrob

Fiat currency requests are unsorted addressed by issue #680. This PR closes #682 too, sorry made a mistake on my branch.

2023-12-12 19:55 UTC, dangeross requested changes
Looks good, just one typo to fix

2023-12-12 19:55 UTC, dangeross commented on libs/sdk-core/src/breez_services.rs
> +    /// List is sorted by the canonical name of the currnecy
```suggestion
    /// List is sorted by the canonical name of the currency
```

2023-12-12 20:05 UTC, dangeross approved these changes

2023-12-13 17:58 UTC, roeierez approved these changes
LGTM

2023-12-13 17:58 UTC, merged