Automatic channel setup fee limit - Android extension #825
breez/breez-sdk pull request #826
Opened 2024-02-28 10:02 UTC by erdemyerebasmaz

This PR makes automatic channel setup fee limit configurable via ExtensionSettings.

2024-02-28 15:41 UTC, roeierez requested changes

2024-02-28 15:41 UTC, roeierez commented on libs/sdk-bindings/bindings-android/lib/src/main/kotlin/breez_sdk_notification/ForegroundService.kt
> +    abstract fun getExtensionSettings(): ExtensionSettings?
NIT: I think the term extension is a bit confusing. Perhaps `getServiceConfig` or `getServiceSettings` ?

2024-02-28 15:41 UTC, roeierez commented on libs/sdk-bindings/bindings-android/lib/src/main/kotlin/breez_sdk_notification/job/LnurlPayInvoice.kt
> +                    ExtensionSettings.instance.autoChannelSetupFeeLimitMsats,
Using a global singleton here is problematic. It makes the getServiceSettings abstraction redundant.
Also IMO it makes the input flow to the jobs complicated. A unified flow where all the job input is defined and passed in one place is better, this is why I think passing it as an argument on the intent makes sense.

2024-02-29 09:07 UTC, dangeross commented on libs/sdk-bindings/bindings-android/lib/src/main/kotlin/breez_sdk_notification/job/LnurlPayInfo.kt
> +                    nodeState.inboundLiquidityMsats
I think this confuses the user acceptable fee limit with the max amount that can be received. 

If a fee limit is set, the max sendable can be nodeState.maxReceivableMsat (minus channelsBalanceMsat?). Then before creating the invoice in the next step, if the amount is over the channelsBalanceMsat check the openChannelFee result to see if the feeMsat is within the user fee limit.

2024-02-29 12:56 UTC, erdemyerebasmaz commented
Closed in favor of #833

2024-02-29 12:56 UTC, closed without merging